
server:
  port: 8084
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/deneme_project
    username: root
    password: 3871
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      '[hibernate.format_sql]': true

odevdeneme:
  app:
    jwtSecret: odevDeneme@12
    jwtExpirationMs: 86400000

logging:
  file:
    name: logs/odevdeneme.log
  pattern:
    file: "%d %-5level [%thread] %logger:%msg%n"

  level:
    '[org.springframework.web]': INFO
    '[org.hibernate]': INFO
    '[com.greenrent]': DEBUG